### ISSUE TITLE
Review GPS behaviour

### ISSUE THREAD

**Issue by ifirmawan** [akvo/nmis-mobile#112]
## TODO/DONE

- [x] The fetching of GPS should be dependent on user action
- [x]  Add the "use selected location" button  on the Map view
- [x] Add radius param to handle valid response, eg: 20 (in meters)
- [x] Update unit tests

## Bug fix

- [ ][Fix GPS accuracy behaviour]( https://akvo.slack.com/archives/C05C0RZUFLK/p1691497172833279?thread_ts=1691496886.075319&cid=C05C0RZUFLK)
