### ISSUE TITLE
Add User Page

### ISSUE THREAD

**Issue by ifirmawan** [akvo/nmis-mobile#27]
## TODO/DONE

- [x] User Profile Creation
- [x] Unit test

Reference: https://wiki.cloud.akvo.org/books/mobile-app-for-national-management-information-system/page/low-level-design#bkmrk-add-user-page

### Additional

- [x] Add active column
- [x] Users list
- [ ] Unit test users list
- [x] Update AddUser Page to handle first user
- [x] Switch user
