### ISSUE TITLE
Create an initial page & add app dependencies

### ISSUE THREAD

**Issue by ifirmawan** [akvo/nmis-mobile#5]
## TODO/DONE

- [ ] Install [Formik](https://formik.org/)
- [ ] Install [React Native Elements](https://reactnativeelements.com/)
- [ ] Create initial page
