### ISSUE TITLE
Question Translation and Tooltip

### ISSUE THREAD

**Issue by ifirmawan** [akvo/nmis-mobile#58]
## TODO/DONE

Translation for
- [ ] Question Text
- [ ] Tooltip text
- [ ] Options
- [ ] Error message

### Test cases

- [ ]  should translate Question Text
- [ ] should translate tooltip text
- [ ]  should translate Options
- [ ]  should translate Error message with Yup
- [ ]  should update translation on language change
- [ ]  should fallback to default language when translation is not available
