### ISSUE TITLE
UI literals translation

### ISSUE THREAD

**Issue by ifirmawan** [akvo/nmis-mobile#88]
## TODO/DONE

- [ ] Create UItext library
- [ ] Replace all hardcoded text
- [ ] [Error message customization](https://github.com/jquense/yup#error-message-customization)
