### ISSUE TITLE
Implement app settings menu items

### ISSUE THREAD

**Issue by ifirmawan** [akvo/nmis-mobile#98]
## TODO/DONE

- [ ] Implement Settings: Sync wifi
- [x] Implement Settings: Sync interval
- [x] Remove dark mode and font size
- [x] Put lang at higher level
- [x] Change server to Advanced
- [x] Remove kebab from settings
- [x] Center settings
- [x] Hidden kebab menu for first User
